train_indices : null
num_workers: 16
num_epochs: 75
batch_size: 4
num_steps_per_epoch: 250
lr: 0.000001
weight_decay: 0.0001
sched: 
    max_epoch: 75
    warmup_max: 10
    multiplier: 100
    update_interval: "epoch"
    update_freq: 1
loss: 
    normalize_fct: null
    reduction: "mean"
    alpha_CE: 0.5
    weighted_CE: false
    n_classes: null
    scale_loss: false
additional_params: null
transform:
    rotation: 10
    gauss_noise: 
        std: 0.01
sampling:
    budget: 10
    num_cycles: 20