strategy: "TTA"
sampling_params: 
  num_inferences: 8
  uncertainty_metric: "JSD"
  alpha: 0.5
  transform:
    rotation: 10
    gauss_noise: 
        std: 0.01
  RandomPacks: 
    resampling: False
    num_groups: null    # If resampling is True
    aggregation: "mean"